### ISSUE TITLE
[PE-D][Tester A] Employee's details alignment is off upon Launch

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-W09-4/tp#178]
![image.png](https://raw.githubusercontent.com/astraxq/ped/main/files/43f43e9a-4a9d-4238-9b2d-df2c59abfc9f.png)

Steps to replicate: 
1. run java -jar ExecutivePro.jar
2. Application launches this state.

Resizing the window will rectify this issue. 
One likely cause might be the screen resolution in my environment that caused this issue (I'm using a monitor)

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: astraxq/ped#1

**Comment by yanlings** [comment]
Mentioned in DG
