### ISSUE TITLE
[PE-D][Tester E] leave bug

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-W09-4/tp#180]
![image.png](https://raw.githubusercontent.com/sarthak181/ped/main/files/14475ed0-4bf4-45a0-ba36-4fcfc2af609f.png)

"Leave .... integer more than 1". It should be "more than 0" because typing in 1 also works. 

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: sarthak181/ped#1

**Comment by abenx162** [comment]
duplicate issue
