### ISSUE TITLE
[PE-D][Tester C] Unable to delete picture

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-W09-4/tp#190]
There isn't a way to delete pictures from the application. I think such a feature could make the product a lot more cohesive. 

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: lywich/ped#5

**Comment by abenx162** [comment]
Pictures should not need to be deleted in normal usage. If necessary, employee image can be updated with a blank image.
