### ISSUE TITLE
[PE-D][Tester C] Greater clarification on payroll

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-W09-4/tp#198]
Initially, I was very confused with how the payroll field works. I was a bit confused why there must be a separation and the UG wasn't very descriptive on it.

The UG also states it can take it any value when negative values don't work.

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: lywich/ped#7

**Comment by gyulong1** [comment]
Fixed by #244
