### ISSUE TITLE
[PE-D][Tester A] batchExport with unhandled invalid file path exception

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-W09-4/tp#210]
![image.png](https://raw.githubusercontent.com/astraxq/ped/main/files/b37056e9-d7af-4e59-a688-ee0297baeca7.png)

Command to replicate: 
```batchexport C:```

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: astraxq/ped#8

**Comment by yanlings** [comment]
Fix in DG
