### ISSUE TITLE
[PE-D][Tester A] Irresponsive and Laggy File Explorer [setpicture]

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-W09-4/tp#216]
Very difficult to navigate in the file explorer, screen just freezes before "teleporting" to another frame.

Might have to consider other build in libraries like ```FileChooser``` e.g

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: astraxq/ped#11

**Comment by abenx162** [comment]
Fixed by #219
