### ISSUE TITLE
[PE-D][Tester C] Some csv file problems? 

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-W09-4/tp#217]
I attempted to imitate CSV passing around by batchadding a different csv file. 

Step 1. add n/John Doe p/98765432 d/Marketing pr/1000 15 e/johnd@example.com a/John street, block 123, #01-01

Step 2. batchexport test.csv

Step 3. Open .csv, Ctrl-c the data and save it in a separate .csv file call Book1.csv

Step 4. batchadd test.csv (success)

Step 5. clear

Step 6. batchadd Book1.csv (fails) 

I attempted to save Book1.csv in a few different csv format but none works. The Book1.csv in the picture below is saved as CSV (comma delimited) similar to test.csv. Worthy to note that a copy of test.csv works (copy paste test.csv) but copying its data into a different csv doesn't. Unfortunately, I am unable to upload csv files here.

I'm not too well versed with excel formats, especially since I did not look at the code to see how csv formats are parsed. But if this was a format error I think this should be in the documentation somewhere so people like me will know what to do.

![image.png](https://raw.githubusercontent.com/lywich/ped/main/files/16b17c0d-fe0e-43c8-a770-d2227433f71b.png)

![image.png](https://raw.githubusercontent.com/lywich/ped/main/files/e7391b52-fc45-4204-89c4-4ccc51633b64.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: lywich/ped#11

**Comment by JunHao247** [comment]
Duplicate issue as #183
